name: Run Unit Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  unit-test:
    name: Run Vitest tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm run test:unit
